In [13]:
# 设计一个接受输入并计算张量降维的层

import torch
import torch.nn as nn

class TensorReductionLayer(nn.Module):
    def __init__(self, n_inputs, n_outputs):
        super().__init__()
        self.weight = nn.Parameter(torch.randn([n_outputs, n_inputs, n_inputs]))
    
    def forward(self, x):
        batch_size = x.shape[0]
        y = torch.zeros([batch_size, n_outputs], dtype=torch.float32)
        
        for b in range(batch_size):
            for k in range(n_outputs):
                y[b, k] = torch.mm(x[b].view([1, -1]), torch.mm(self.weight[k], x[b].view([-1, 1])))
        
        return y
    
n_inputs, n_outputs = 4, 3
layer = TensorReductionLayer(n_inputs, n_outputs)

x = torch.randn([5, n_inputs])
y = layer(x)
print(x)
print(y)

tensor([[-1.4206, -0.2444, -0.6904, -0.2298],
        [-0.3227,  0.2754, -0.1739, -0.7486],
        [-0.1886, -1.4495, -1.1214,  0.6101],
        [-0.0921, -1.1953,  0.7416,  0.3623],
        [ 0.5132,  0.0405,  0.3808,  0.5667]])
tensor([[ 3.7625,  2.4491,  2.7370],
        [ 0.3383,  1.5300,  0.2912],
        [ 0.0647, -0.3227, -1.6080],
        [-0.0858,  1.0766, -2.4401],
        [ 0.5617,  1.0075,  0.9118]], grad_fn=<CopySlices>)


In [14]:
# 设计一个返回输入数据的傅立叶系数前半部分的层

import torch
import torch.nn as nn

class FourierTransformLayer(nn.Module):
    def __init__(self):
        super(FourierTransformLayer, self).__init__()

    def forward(self, x):
        fft_result = torch.fft.fft(x)
        half_size = fft_result.size(-1) // 2 + 1
        return fft_result[..., :half_size]

layer = FourierTransformLayer()
    
x = torch.randn(5, 8)
y = layer(x)
print(x)
print(y)

tensor([[ 0.1782,  0.1369,  0.0417, -1.7692, -0.8856, -0.2775, -0.4760,  0.6327],
        [ 1.4307,  0.3900,  0.8136,  0.3715,  0.1592,  0.0591,  0.6442,  0.8247],
        [-1.1185, -0.3950, -0.1253, -0.4581, -0.5923,  1.0534,  0.8306, -1.3233],
        [-0.4406,  0.2232,  1.6072, -0.4072, -0.3573, -0.3237, -0.0456,  0.1531],
        [ 1.0388,  0.7428, -0.6037,  0.4988,  2.0147, -0.3290,  0.3865,  1.3041]])
tensor([[-2.4187+0.0000j,  3.0553+0.8877j, -0.2732-0.9959j, -0.9276+1.9231j,
          0.1354+0.0000j],
        [ 4.6930+0.0000j,  1.8260-0.0829j,  0.1322+0.7470j,  0.7170+0.2559j,
          1.4024+0.0000j],
        [-2.1284+0.0000j, -2.1622+1.3683j, -2.4161-2.4397j,  1.1097-0.5435j,
          0.1176+0.0000j],
        [ 0.4091+0.0000j,  0.6997-1.6434j, -2.3595-0.1536j, -0.8663+1.6623j,
          1.1182+0.0000j],
        [ 5.0530+0.0000j,  0.3514+0.8016j,  3.2707+1.3890j, -2.3032-1.1786j,
          0.6196+0.0000j]])


In [18]:
torch.cuda.device_count()

1