In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [11]:
# 加载和保存张量

x = torch.tensor([1, 2, 3])
torch.save(x, 'x_file')
x2 = torch.load('x_file', weights_only=True)
print(x2)

y = torch.zeros(4)
torch.save([x, y], 'x_files')
x2, y2 = torch.load('x_files', weights_only=True)
print(x2, y2)

mydict = {'x': x, 'y': y}
torch.save(mydict, 'mydict')
mydict2 = torch.load('mydict', weights_only=True)
print(mydict2)

tensor([1, 2, 3])
tensor([1, 2, 3]) tensor([0., 0., 0., 0.])
{'x': tensor([1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}


In [17]:
# 加载和保存模型参数

class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(20, 256)
        self.layer2 = nn.Linear(256, 10)
    
    def forward(self, x):
        return self.layer2(F.relu(self.layer1(x)))

mlp = MLP()
torch.save(mlp.state_dict(), 'mlp_params') # 只能存模型的参数

X = torch.randn([2, 20])
Y = mlp(X)

clone = MLP() # 需要先建立源模型
clone.load_state_dict(torch.load('mlp_params', weights_only=True)) # 再读入模型参数
clone.eval() # 预测模式

Y2 = mlp(X)

print(Y == Y2)

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])
