In [1]:
import torch

### Tensor on GPU

In [4]:
x = torch.arange(12, dtype=torch.float32).view(3, 4)

if torch.cuda.is_available():
    device = torch.device("cuda")
    
y = torch.ones_like(x, device=device)
x = x.to(device)
z = x + y
x, y, z, z.to("cpu", torch.double)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]], device='cuda:0'),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]], device='cuda:0'),
 tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]], device='cuda:0'),
 tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]], dtype=torch.float64))