In [1]:
import torch

### 2.3.1 标量

In [3]:
x = torch.Tensor([5.0])
y = torch.Tensor([2.5])
x + y, x - y, x * y, x / y, y ** x

(tensor([7.5000]),
 tensor([2.5000]),
 tensor([12.5000]),
 tensor([2.]),
 tensor([97.6562]))

### 2.3.2 向量

In [4]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [5]:
x[3]

tensor(3)

#### 2.3.2.1 长度、维度和形状

In [7]:
len(x), x.shape

(4, torch.Size([4]))

In [52]:
# 对张量len(A)返回第一维的长度
A = torch.arange(24).reshape(2, 3, 4)
len(A)

2

### 2.3.3 矩阵

In [9]:
A = torch.arange(12).reshape(3, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [10]:
# 矩阵转置
A.T

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

In [47]:
# 对称矩阵的转置等于自身
B = torch.Tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [48]:
# 转置的转置等于自身
A.T.T == A

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [49]:
# 转置的和等于和的转置
A = torch.arange(9).reshape(3, 3)
A.T + B.T == (A + B).T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [51]:
# 矩阵和其转置的和总是对称的
C = A + A.T
C, C == C.T

(tensor([[ 0,  4,  8],
         [ 4,  8, 12],
         [ 8, 12, 16]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

### 2.3.4 张量
张量是描述具有任意数量轴的$n$维数组的通用方法

In [13]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

### 2.3.5 张量算法的基本性质

In [14]:
A = torch.arange(20, dtype=torch.float32).reshape(4, 5)
B = A.clone() # 重新分配内存克隆
A, B, A + B

(tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.,  8.],
         [10., 12., 14., 16., 18.],
         [20., 22., 24., 26., 28.],
         [30., 32., 34., 36., 38.]]))

In [15]:
# 按位乘
A * B

tensor([[  0.,   1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.,  81.],
        [100., 121., 144., 169., 196.],
        [225., 256., 289., 324., 361.]])

In [16]:
# 张量加/乘标量是每一个位置上都加，且不改变张量的形状
a = 2
X = torch.arange(24).reshape(2, 3, 4)
X + a, (X * a).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

### 2.3.6 降维

In [18]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [19]:
A.shape, A.sum()

(torch.Size([4, 5]), tensor(190.))

In [20]:
A_sum_axis0 = A.sum(axis=0)
A, A_sum_axis0, A_sum_axis0.shape

(tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]]),
 tensor([30., 34., 38., 42., 46.]),
 torch.Size([5]))

In [21]:
A_sum_axis1 = A.sum(axis=1)
A, A_sum_axis1, A_sum_axis1.shape

(tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]]),
 tensor([10., 35., 60., 85.]),
 torch.Size([4]))

In [22]:
A.sum(axis=[0, 1]) # 结果和A.sum()相同

tensor(190.)

In [57]:
# 在某一轴求和后，该轴被降维
B = torch.arange(24, dtype=torch.float32).reshape(2, 3, 4)
B, B.sum(axis=0), B.sum(axis=1), B.sum(axis=2)

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]],
 
         [[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.]]]),
 tensor([[12., 14., 16., 18.],
         [20., 22., 24., 26.],
         [28., 30., 32., 34.]]),
 tensor([[12., 15., 18., 21.],
         [48., 51., 54., 57.]]),
 tensor([[ 6., 22., 38.],
         [54., 70., 86.]]))

In [24]:
# 求平均值
A.mean(), A.sum() / A.numel()

(tensor(9.5000), tensor(9.5000))

In [25]:
# 延轴处理维度
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([ 7.5000,  8.5000,  9.5000, 10.5000, 11.5000]),
 tensor([ 7.5000,  8.5000,  9.5000, 10.5000, 11.5000]))

#### 2.3.6.1 非降维求和

In [29]:
# keepdims=True表示保持维度，即不降维
A.sum(axis=1), A.sum(axis=1, keepdims=True)

(tensor([10., 35., 60., 85.]),
 tensor([[10.],
         [35.],
         [60.],
         [85.]]))

In [30]:
# cumsum()计算累积和，不降维
A, A.cumsum(axis=1)

(tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  3.,  6., 10.],
         [ 5., 11., 18., 26., 35.],
         [10., 21., 33., 46., 60.],
         [15., 31., 48., 66., 85.]]))

### 2.3.7 点积

In [31]:
# 向量点积
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [32]:
# 也可以通过求和计算
torch.sum(x * y)

tensor(6.)

### 2.3.8 矩阵-向量积

In [40]:
# 矩阵的列数要和向量元素个数相同
A = A.reshape(-1, 4)
A, x, torch.mv(A, x)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]),
 tensor([ 14.,  38.,  62.,  86., 110.]))

### 2.3.9 矩阵-矩阵乘法

In [43]:
# A的列数要等与B的行数
B = torch.arange(12, dtype=torch.float32).reshape(4, 3)
A, B, torch.mm(A, B)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.],
         [ 3.,  4.,  5.],
         [ 6.,  7.,  8.],
         [ 9., 10., 11.]]),
 tensor([[ 42.,  48.,  54.],
         [114., 136., 158.],
         [186., 224., 262.],
         [258., 312., 366.],
         [330., 400., 470.]]))

### 2.3.10 范数
向量的$L_p$范数为$||x||_p=(\sum_{i=1}^n|x_i|^p)^{1/p}$ <br>
矩阵的Frobenius范数为$||X||_F=\sqrt{\sum_{i=1}^m\sum_{j=1}^n x_{ij}^2}$

In [44]:
# L2范数为欧式距离
u = torch.Tensor([-3.0, 4.0])
torch.norm(u)

tensor(5.)

In [45]:
# L1范数为向量所有元素绝对值的和
abs(u).sum()

tensor(7.)

In [46]:
# 矩阵的Frobenius范数
torch.norm(torch.ones(3, 3))

tensor(3.)

In [58]:
torch.norm(torch.ones(3, 3, 3, 3))

tensor(9.)